### ISSUE TITLE
列表后的内容自动换行

### ISSUE THREAD

**Issue by ayueme** [siyuan-note/appearance#1]
两个问题：
1. 不管是有序列表还是无序列表，后面的内容不能紧跟，会自动换到下一行；
2. 调整文件树面板的宽度大于某一个距离时，主界面2侧的留白宽度不一样。

如图所示：
![无标题](https://user-images.githubusercontent.com/58946586/106390273-82bca980-6422-11eb-9708-b2ed6269179d.png)

**Comment by 88250** [comment]
你好，请给该主题仓库提 issue，非常感谢。
